Repository 4Ailen/backend, pull requests merged in 2023-08, with the labels that each got.

#172 Refactor/#170 matching logic
  membership/src/main/java/com/aliens/friendship/domain/match/business/MatchBusiness.java
  membership/src/main/java/com/aliens/friendship/domain/match/business/MatchSaveBusiness.java
  membership/src/main/java/com/aliens/friendship/domain/match/converter/MatchConverter.java
  membership/src/test/java/com/aliens/friendship/applicant/controller/IntegrationApplicationControllerTest.java
  membership/src/test/java/com/aliens/friendship/emailauthentication/controller/IntegrationEmailAuthenticationControllerTest.java
Labels: ⚙️refactor, 리뷰 얼마 안걸려요!!

#174 Feat/#173 email applicant api
  db/src/main/java/com/aliens/db/applicant/entity/ApplicantEntity.java
  membership/build.gradle
  membership/src/main/java/com/aliens/friendship/domain/applicant/business/ApplicantBusiness.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/controller/ApplicantController.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/controller/dto/ApplicantResponseDto.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/converter/ApplicantConverter.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/service/ApplicantService.java
  membership/src/main/java/com/aliens/friendship/domain/emailauthentication/controller/EmailAuthenticationController.java
  membership/src/main/java/com/aliens/friendship/domain/emailauthentication/service/EmailAuthenticationService.java
  membership/src/main/java/com/aliens/friendship/domain/member/converter/MemberConverter.java
  membership/src/test/java/com/aliens/friendship/applicant/controller/IntegrationApplicationControllerTest.java
  membership/src/test/java/com/aliens/friendship/emailauthentication/controller/IntegrationEmailAuthenticationControllerTest.java
Labels: 🧪test, 🌟feat, ⚙️refactor, 리뷰 얼마 안걸려요!!

#178 Feat/#177 fcm token 등록, 삭제 기능 추가
  db/build.gradle
  db/src/main/java/com/aliens/db/auth/entity/FcmTokenEntity.java
  db/src/main/java/com/aliens/db/auth/repository/FcmTokenRepository.java
  gradlew
  membership/build.gradle
  membership/src/main/java/com/aliens/friendship/domain/auth/business/AuthBusiness.java
  membership/src/main/java/com/aliens/friendship/domain/auth/controller/AuthController.java
  membership/src/main/java/com/aliens/friendship/domain/auth/exception/AuthExceptionCode.java
  membership/src/main/java/com/aliens/friendship/domain/auth/exception/AuthExceptionHandler.java
  membership/src/main/java/com/aliens/friendship/domain/auth/exception/FcmTokenNotFoundException.java
  membership/src/main/java/com/aliens/friendship/domain/auth/exception/InvalidFcmTokenException.java
  membership/src/main/java/com/aliens/friendship/domain/auth/filter/JwtAuthenticationFilter.java
  membership/src/main/java/com/aliens/friendship/domain/auth/service/AuthService.java
  membership/src/main/java/com/aliens/friendship/global/util/HeaderUtil.java
  membership/src/test/java/com/aliens/friendship/applicant/controller/IntegrationApplicationControllerTest.java
  membership/src/test/java/com/aliens/friendship/auth/business/MockAuthBusinessTest.java
  membership/src/test/java/com/aliens/friendship/auth/controller/IntegrationAuthControllerTest.java
  membership/src/test/java/com/aliens/friendship/block/controller/IntegrationBlockControllerTest.java
  membership/src/test/java/com/aliens/friendship/member/controller/IntegrationMemberControllerTest.java
  membership/src/test/java/com/aliens/friendship/report/controller/IntegrationReportControllerTest.java
Labels: 🌟feat

#179 Fix/#175 after module 모듈화 이후 이슈 수정
  membership/src/main/java/com/aliens/friendship/domain/applicant/converter/ApplicantConverter.java
Labels: 🔧fix, 리뷰 얼마 안걸려요!!

#185 Fix/#184 modify prefer languages
  membership/src/main/java/com/aliens/friendship/domain/applicant/business/ApplicantBusiness.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/service/ApplicantService.java
  membership/src/main/java/com/aliens/friendship/domain/auth/service/AuthService.java
  membership/src/main/java/com/aliens/friendship/domain/match/exception/MatchExceptionCode.java
  membership/src/main/java/com/aliens/friendship/domain/match/exception/MatchExceptionHandler.java
  membership/src/main/java/com/aliens/friendship/domain/match/exception/MatchRequestNotSubmitted.java
  membership/src/main/java/com/aliens/friendship/domain/match/exception/MatchingCompletedException.java
  membership/src/test/java/com/aliens/friendship/applicant/controller/IntegrationApplicationControllerTest.java
  membership/src/test/java/com/aliens/friendship/chat/controller/IntegrationChatControllerTest.java
Labels: 🔧fix, 리뷰 얼마 안걸려요!!

#187 Fix/#186 withdrawal chatting room
  membership/src/main/java/com/aliens/friendship/domain/member/service/MemberService.java
Labels: 🔧fix, 리뷰 얼마 안걸려요!!

#189 fix: 회원 비밀번호 변경 예외 추가 및 적용
  membership/src/main/java/com/aliens/friendship/domain/member/exception/IdenticalPasswordException.java
  membership/src/main/java/com/aliens/friendship/domain/member/exception/MemberExceptionCode.java
  membership/src/main/java/com/aliens/friendship/domain/member/exception/MemberExceptionHandler.java
  membership/src/main/java/com/aliens/friendship/domain/member/service/MemberService.java
Labels: 🔧fix, 리뷰 얼마 안걸려요!!

#191 refactor : 한국어,영어 지원해주는 안내문으로 메일 내용 변경
  membership/src/main/java/com/aliens/friendship/domain/emailauthentication/service/EmailAuthenticationService.java
  membership/src/main/java/com/aliens/friendship/domain/member/service/MemberService.java
Labels: ⚙️refactor

#194 Feat/#154 rest docs
  membership/build.gradle
  membership/src/docs/asciidoc/index.adoc
  membership/src/main/java/com/aliens/friendship/domain/member/service/MemberService.java
  membership/src/main/java/com/aliens/friendship/global/config/security/SecurityConfig.java
  membership/src/main/resources/static/docs/index.html
  membership/src/main/resources/static/docs/overview.html
  membership/src/test/java/com/aliens/friendship/admin/IntegrationAdminControllerTest.java
  membership/src/test/java/com/aliens/friendship/applicant/controller/IntegrationApplicationControllerTest.java
  membership/src/test/java/com/aliens/friendship/auth/controller/IntegrationAuthControllerTest.java
  membership/src/test/java/com/aliens/friendship/block/controller/IntegrationBlockControllerTest.java
  membership/src/test/java/com/aliens/friendship/chat/controller/IntegrationChatControllerTest.java
  membership/src/test/java/com/aliens/friendship/emailauthentication/controller/IntegrationEmailAuthenticationControllerTest.java
  membership/src/test/java/com/aliens/friendship/member/controller/IntegrationMemberControllerTest.java
  membership/src/test/java/com/aliens/friendship/report/controller/IntegrationReportControllerTest.java
Labels: 🧪test, 📄docs, 천천히 리뷰해주세요~

#198 Feat/#197 monitoring config
  membership/build.gradle
  membership/src/main/java/com/aliens/friendship/global/config/httptrace/HttpTraceConfig.java
  membership/src/main/java/com/aliens/friendship/global/config/security/SecurityConfig.java
Labels: 🌟feat, 리뷰 얼마 안걸려요!!
