Repository 4Ailen/backend, pull requests merged in 2023-09, with the labels that each got.

#207 Feat/#203 board fcm
  .gitignore
  db/src/main/java/com/aliens/db/auth/repository/FcmTokenRepository.java
  db/src/main/java/com/aliens/db/communityarticlelike/repository/CommunityArticleLikeRepository.java
  db/src/main/java/com/aliens/db/marketarticle/MarketArticleStatus.java
  db/src/main/java/com/aliens/db/marketarticle/ProductStatus.java
  db/src/main/java/com/aliens/db/marketbookmark/repository/MarketBookmarkRepository.java
  db/src/main/java/com/aliens/db/personalNotice/entity/PersonalNoticeEntity.java
  db/src/main/java/com/aliens/db/personalNotice/repository/PersonalNoticeRepository.java
  membership/build.gradle
  membership/src/main/java/com/aliens/friendship/domain/article/comment/controller/CommunityArticleCommentController.java
  membership/src/main/java/com/aliens/friendship/domain/article/comment/controller/MarketArticleCommentController.java
  membership/src/main/java/com/aliens/friendship/domain/article/comment/service/CommunityArticleCommentService.java
  membership/src/main/java/com/aliens/friendship/domain/article/comment/service/MarketArticleCommentService.java
  membership/src/main/java/com/aliens/friendship/domain/article/community/controller/CommunityArticleController.java
  membership/src/main/java/com/aliens/friendship/domain/article/community/dto/UpdateLikeResponse.java
  membership/src/main/java/com/aliens/friendship/domain/article/community/service/CommunityArticleService.java
  membership/src/main/java/com/aliens/friendship/domain/article/market/controller/MarketArticleController.java
  membership/src/main/java/com/aliens/friendship/domain/article/market/dto/CreateMarketArticleRequest.java
  membership/src/main/java/com/aliens/friendship/domain/article/market/dto/UpdateBookmarkResponse.java
  membership/src/main/java/com/aliens/friendship/domain/article/market/service/MarketArticleService.java
  membership/src/main/java/com/aliens/friendship/domain/fcm/converter/FcmMessageConverter.java
  membership/src/main/java/com/aliens/friendship/domain/fcm/service/FcmService.java
  membership/src/main/java/com/aliens/friendship/domain/personalNotice/controller/PersonalNoticeController.java
  membership/src/main/java/com/aliens/friendship/domain/personalNotice/dto/PersonalNoticesDto.java
  membership/src/main/java/com/aliens/friendship/domain/personalNotice/service/PersonalNoticeService.java
  membership/src/main/java/com/aliens/friendship/global/config/fcm/FirebaseInit.java
  membership/src/main/java/com/aliens/friendship/global/config/fcm/FirebaseMessagingWrapper.java
  membership/src/main/java/com/aliens/friendship/global/config/fcm/FirebaseMessagingWrapperImpl.java
Labels: 🌟feat, 🔀merge, 리뷰 진짜 급함!!!!

#204 Refactor v2/#202 matching
  db/src/main/java/com/aliens/db/member/entity/MemberEntity.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/business/ApplicantBusiness.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/controller/ApplicantController.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/service/ApplicantService.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/service/MatchingInfoService.java
  membership/src/main/java/com/aliens/friendship/domain/auth/model/UserPrincipal.java
  membership/src/main/java/com/aliens/friendship/domain/chat/business/ChatBusiness.java
  membership/src/main/java/com/aliens/friendship/domain/chat/service/ChattingJwtTokenUtil.java
  membership/src/main/java/com/aliens/friendship/domain/match/business/MatchBusiness.java
  membership/src/main/java/com/aliens/friendship/domain/match/business/MatchSaveBusiness.java
  membership/src/main/java/com/aliens/friendship/domain/member/service/MemberService.java
  membership/src/test/java/com/aliens/friendship/applicant/business/ApplicantBusinessTest.java
  membership/src/test/java/com/aliens/friendship/applicant/controller/IntegrationApplicationControllerTest.java
  membership/src/test/java/com/aliens/friendship/auth/business/MockAuthBusinessTest.java
Labels: ⚙️refactor

#206 Feat/#205 my list
  db/src/main/java/com/aliens/db/communityarticle/entity/CommunityArticleEntity.java
  db/src/main/java/com/aliens/db/communityarticle/repository/CommunityArticleRepository.java
  db/src/main/java/com/aliens/db/communityarticlecomment/entity/CommunityArticleCommentEntity.java
  db/src/main/java/com/aliens/db/communityarticlecomment/repository/CommunityArticleCommentRepository.java
  db/src/main/java/com/aliens/db/communityarticleimage/entity/CommunityArticleImageEntity.java
  db/src/main/java/com/aliens/db/communityarticlelike/entity/CommunityArticleLikeEntity.java
  db/src/main/java/com/aliens/db/marketarticle/entity/MarketArticleEntity.java
  db/src/main/java/com/aliens/db/marketarticle/repository/MarketArticleRepository.java
  db/src/main/java/com/aliens/db/marketarticlecomment/entity/MarketArticleCommentEntity.java
  db/src/main/java/com/aliens/db/marketarticlecomment/repository/MarketArticleCommentRepository.java
  db/src/main/java/com/aliens/db/marketbookmark/entity/MarketBookmarkEntity.java
  db/src/main/java/com/aliens/db/matching/entity/MatchingEntity.java
  membership/src/main/java/com/aliens/friendship/domain/article/controller/ArticleController.java
  membership/src/main/java/com/aliens/friendship/domain/article/dto/ArticleDto.java
  membership/src/main/java/com/aliens/friendship/domain/article/market/dto/MarketArticleDto.java
  membership/src/main/java/com/aliens/friendship/domain/article/service/ArticleService.java
Labels: 🌟feat, ⚙️refactor

#209 Refactor/#208 status api
  db/src/main/java/com/aliens/db/member/entity/MemberEntity.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/business/ApplicantBusiness.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/controller/ApplicantController.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/converter/ApplicantConverter.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/service/MatchingInfoService.java
  membership/src/main/java/com/aliens/friendship/domain/article/dto/ArticleDto.java
Labels: ⚙️refactor

#213 Refactor/#212좋아요, 찜한 게시글 조회 API 합병
  membership/src/main/java/com/aliens/friendship/domain/article/community/controller/CommunityArticleController.java
  membership/src/main/java/com/aliens/friendship/domain/article/community/service/CommunityArticleService.java
  membership/src/main/java/com/aliens/friendship/domain/article/controller/ArticleController.java
  membership/src/main/java/com/aliens/friendship/domain/article/market/controller/MarketArticleController.java
  membership/src/main/java/com/aliens/friendship/domain/article/market/service/MarketArticleService.java
  membership/src/main/java/com/aliens/friendship/domain/article/service/ArticleService.java
Labels: ⚙️refactor

#219 refactor : 전체 게시글 조회시 DESC 적용
  membership/src/main/java/com/aliens/friendship/domain/article/controller/ArticleController.java
  membership/src/main/java/com/aliens/friendship/domain/article/service/ArticleService.java
Labels: 🔧fix

#223 Refactor, Fix: 일반게시판 이미지 없는 경우, 게시글 중복 조회 문제 해결
  membership/src/main/java/com/aliens/friendship/domain/article/community/service/CommunityArticleService.java
  membership/src/main/java/com/aliens/friendship/domain/article/dto/ArticleDto.java
  membership/src/main/java/com/aliens/friendship/domain/article/service/ArticleService.java
Labels: ⚙️refactor
