Repository 4Ailen/backend, pull requests merged in 2023-02, with the labels that each got.

#73 Test/#51jwt test JWT 인증 테스트 코드 작성
  src/main/java/com/aliens/friendship/global/config/jwt/JwtHeaderUtilEnums.java
  src/main/java/com/aliens/friendship/global/config/security/SecurityConfig.java
  src/main/java/com/aliens/friendship/member/controller/APIController.java
  src/main/java/com/aliens/friendship/member/domain/Member.java
  src/main/java/com/aliens/friendship/member/service/MemberService.java
  src/test/java/com/aliens/friendship/jwt/JwtAPITest.java
  src/test/java/com/aliens/friendship/jwt/JwtUtilTest.java
Labels: 🧪test, ⚙️refactor, 천천히 리뷰해주세요~

#71 feat/#69 join 회원가입 API 추가
  src/main/java/com/aliens/friendship/matching/service/MatchingService.java
  src/main/java/com/aliens/friendship/member/controller/APIController.java
  src/main/java/com/aliens/friendship/member/controller/FileUploadController.java
  src/main/java/com/aliens/friendship/member/controller/MemberController.java
  src/main/java/com/aliens/friendship/member/controller/NationalityController.java
  src/main/java/com/aliens/friendship/member/controller/dto/JoinDto.java
  src/main/java/com/aliens/friendship/member/controller/dto/MemberInfoDto.java
  src/main/java/com/aliens/friendship/member/controller/dto/WithdrawalDto.java
  src/main/java/com/aliens/friendship/member/domain/Member.java
  src/main/java/com/aliens/friendship/member/service/FileUploadService.java
  src/main/java/com/aliens/friendship/member/service/MemberService.java
  src/main/java/com/aliens/friendship/member/service/NationalityService.java
  src/main/java/com/aliens/friendship/member/service/ProfileImageService.java
  src/test/java/com/aliens/friendship/member/service/MemberServiceTest.java
  src/test/java/com/aliens/friendship/member/service/NationalityServiceTest.java
  src/test/java/com/aliens/friendship/member/service/ProfileImageServiceTest.java
Labels: 🧪test, 🌟feat, 🪛style, 천천히 리뷰해주세요~

#70 refactor/#49 jpql to querydsl
  build.gradle
  src/main/java/com/aliens/friendship/chatting/repository/ChattingCustomRepository.java
  src/main/java/com/aliens/friendship/chatting/repository/ChattingRepository.java
  src/main/java/com/aliens/friendship/chatting/repository/ChattingRepositoryImpl.java
  src/main/java/com/aliens/friendship/chatting/service/ChattingService.java
  src/main/java/com/aliens/friendship/global/config/querydsl/QuerydslConfig.java
  src/main/java/com/aliens/friendship/member/repository/MemberCustomRepository.java
  src/main/java/com/aliens/friendship/member/repository/MemberRepository.java
  src/main/java/com/aliens/friendship/member/repository/MemberRepositoryImpl.java
Labels: ⚙️refactor

#72 refactor/#48 add transaction
  src/main/java/com/aliens/friendship/chatting/service/ChattingService.java
  src/main/java/com/aliens/friendship/member/service/MemberService.java
Labels: ⚙️refactor, 리뷰 얼마 안걸려요!!

#80 fix: APIController의 getMemberInfo 함수 수정
  src/main/java/com/aliens/friendship/member/controller/APIController.java
Labels: 🔧fix, 리뷰 얼마 안걸려요!!

#81 feat/#74 birth and age 회원 정보에 만나이, 생년월일 추가
  src/main/java/com/aliens/friendship/member/controller/APIController.java
  src/main/java/com/aliens/friendship/member/controller/MemberController.java
  src/main/java/com/aliens/friendship/member/controller/dto/JoinDto.java
  src/main/java/com/aliens/friendship/member/controller/dto/MemberInfoDto.java
  src/main/java/com/aliens/friendship/member/domain/Member.java
  src/main/java/com/aliens/friendship/member/service/MemberService.java
  src/test/java/com/aliens/friendship/jwt/JwtAPITest.java
  src/test/java/com/aliens/friendship/jwt/JwtUtilTest.java
  src/test/java/com/aliens/friendship/member/service/MemberServiceTest.java
Labels: 🌟feat
