Repository 4Ailen/backend, pull requests merged in 2023-05, with the labels that each got.

#120 feat/BACKEND-37 프로필 이미지가 없이 회원가입이 가능하도록 수정
  src/main/java/com/aliens/friendship/member/service/ProfileImageService.java
  src/main/java/com/aliens/friendship/member/validation/ProfileImageValidator.java
  src/test/java/com/aliens/friendship/member/controller/MemberControllerTest.java
  src/test/java/com/aliens/friendship/member/service/MemberServiceTest.java
  src/test/java/com/aliens/friendship/member/service/ProfileImageServiceTest.java
Labels: 🧪test, 🌟feat, 리뷰 얼마 안걸려요!!

#113 feat/#111 회원탈퇴 기능 수정
  src/main/java/com/aliens/friendship/matching/domain/Applicant.java
  src/main/java/com/aliens/friendship/matching/domain/BlockingInfo.java
  src/main/java/com/aliens/friendship/matching/domain/Matching.java
  src/main/java/com/aliens/friendship/matching/repository/BlockingInfoRepository.java
  src/main/java/com/aliens/friendship/matching/service/MatchingInfoService.java
  src/main/java/com/aliens/friendship/matching/service/MatchingService.java
  src/main/java/com/aliens/friendship/member/controller/APIController.java
  src/main/java/com/aliens/friendship/member/controller/MemberController.java
  src/main/java/com/aliens/friendship/member/domain/Member.java
  src/main/java/com/aliens/friendship/member/service/MemberService.java
  src/test/java/com/aliens/friendship/chatting/repository/MatchingRepositoryImplTest.java
  src/test/java/com/aliens/friendship/jwt/JwtUtilTest.java
  src/test/java/com/aliens/friendship/matching/service/MatchingInfoServiceTest.java
  src/test/java/com/aliens/friendship/matching/service/MemberFixture.java
  src/test/java/com/aliens/friendship/member/controller/MemberControllerTest.java
  src/test/java/com/aliens/friendship/member/service/MemberServiceTest.java
Labels: 🧪test, 🌟feat, ⚙️refactor, 천천히 리뷰해주세요~

#123 Feat/#111 matching withdraw -> develop 브랜치 머지
  files/04bfbdc6-1bb7-44fb-8b51-7fc5997feda8_ProfileImage.jpg
  files/11db4b56-36f0-4f88-866c-850e65075b44_ProfileImage.jpg
  files/2ed93e15-75fe-4975-89bc-8bacf3701226_ProfileImage.jpg
  files/34129f10-cf63-4c85-9fd7-2e2f6423fc76_ProfileImage.jpg
  files/4832cd10-17af-4e00-8549-61cf6cf34954_ProfileImage.jpg
  files/543fefd8-ef36-4efc-9f57-6d0dc1a623fa_ProfileImage.jpg
  files/57552582-b3ec-49eb-9443-1b45c4bf32d9_ProfileImage.jpg
  files/ccc1ccc5-bdd1-4feb-ad41-fe522bbb1c83_ProfileImage.jpg
  files/fcf9540a-6929-4cfe-9b35-825626034f09_ProfileImage.jpg
  src/main/java/com/aliens/friendship/domain/matching/domain/Applicant.java
  src/main/java/com/aliens/friendship/domain/matching/domain/BlockingInfo.java
  src/main/java/com/aliens/friendship/domain/matching/domain/Matching.java
  src/main/java/com/aliens/friendship/domain/matching/repository/BlockingInfoRepository.java
  src/main/java/com/aliens/friendship/domain/matching/service/MatchingInfoService.java
  src/main/java/com/aliens/friendship/domain/matching/service/MatchingService.java
  src/main/java/com/aliens/friendship/domain/member/controller/APIController.java
  src/main/java/com/aliens/friendship/domain/member/controller/MemberController.java
  src/main/java/com/aliens/friendship/domain/member/domain/Member.java
  src/main/java/com/aliens/friendship/domain/member/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/com/aliens/friendship/chatting/repository/MatchingRepositoryImplTest.java
  src/test/java/com/aliens/friendship/jwt/JwtUtilTest.java
  src/test/java/com/aliens/friendship/matching/service/MatchingInfoServiceTest.java
  src/test/java/com/aliens/friendship/matching/service/MemberFixture.java
  src/test/java/com/aliens/friendship/member/controller/MemberControllerTest.java
  src/test/java/com/aliens/friendship/member/service/MemberServiceTest.java
Labels: 🔀merge

#126 Hotfix 생성자 수정
  src/main/java/com/aliens/friendship/domain/matching/controller/dto/ReportRequest.java
  src/test/java/com/aliens/friendship/member/controller/MemberControllerTest.java
Labels: ⚙️refactor, 리뷰 얼마 안걸려요!!

#127 hotfix: ProfileImageValidator 수정
  src/main/java/com/aliens/friendship/domain/member/validation/ProfileImageValidator.java
Labels: 🔧fix, 리뷰 얼마 안걸려요!!

#129 feat/Backend-51 회원 관련 정보 삭제 기능 추가
  files/04bfbdc6-1bb7-44fb-8b51-7fc5997feda8_ProfileImage.jpg
  files/11db4b56-36f0-4f88-866c-850e65075b44_ProfileImage.jpg
  files/2ed93e15-75fe-4975-89bc-8bacf3701226_ProfileImage.jpg
  files/34129f10-cf63-4c85-9fd7-2e2f6423fc76_ProfileImage.jpg
  files/4832cd10-17af-4e00-8549-61cf6cf34954_ProfileImage.jpg
  files/543fefd8-ef36-4efc-9f57-6d0dc1a623fa_ProfileImage.jpg
  files/57552582-b3ec-49eb-9443-1b45c4bf32d9_ProfileImage.jpg
  files/ccc1ccc5-bdd1-4feb-ad41-fe522bbb1c83_ProfileImage.jpg
  files/fcf9540a-6929-4cfe-9b35-825626034f09_ProfileImage.jpg
  src/main/java/com/aliens/friendship/domain/matching/domain/Applicant.java
  src/main/java/com/aliens/friendship/domain/matching/domain/BlockingInfo.java
  src/main/java/com/aliens/friendship/domain/matching/domain/Matching.java
  src/main/java/com/aliens/friendship/domain/matching/domain/Report.java
  src/main/java/com/aliens/friendship/domain/member/controller/MemberController.java
  src/main/java/com/aliens/friendship/domain/member/service/MemberService.java
  src/main/java/com/aliens/friendship/global/config/security/SecurityConfig.java
  src/test/java/com/aliens/friendship/member/controller/MemberControllerTest.java
  src/test/java/com/aliens/friendship/member/service/MemberServiceTest.java
Labels: 🧪test, 🌟feat, 리뷰 진짜 급함!!!!

#131 Hotfix 신고 엔티티 수정
  src/main/java/com/aliens/friendship/domain/matching/domain/Report.java
Labels: 🔧fix, 리뷰 진짜 급함!!!!, 리뷰 얼마 안걸려요!!

#130 #128 Chat을 제외한 전 도메인 응답 구조 & 예외 로직 개선
  src/main/java/com/aliens/friendship/domain/emailAuthentication/controller/EmailAuthenticationController.java
  src/main/java/com/aliens/friendship/domain/emailAuthentication/exception/EmailAlreadyRegisteredException.java
  src/main/java/com/aliens/friendship/domain/emailAuthentication/exception/EmailAuthenticationExceptionCode.java
  src/main/java/com/aliens/friendship/domain/emailAuthentication/exception/EmailAuthenticationExceptionHandler.java
  src/main/java/com/aliens/friendship/domain/emailAuthentication/exception/EmailVerificationTimeOutException.java
  src/main/java/com/aliens/friendship/domain/emailAuthentication/service/EmailAuthenticationService.java
  src/main/java/com/aliens/friendship/domain/jwt/exception/JWTExceptionCode.java
  src/main/java/com/aliens/friendship/domain/jwt/exception/JWTExceptionHandler.java
  src/main/java/com/aliens/friendship/domain/jwt/exception/RefreshTokenNotFoundException.java
  src/main/java/com/aliens/friendship/domain/jwt/exception/TokenException.java
  src/main/java/com/aliens/friendship/domain/matching/controller/MatchingController.java
  src/main/java/com/aliens/friendship/domain/matching/exception/ApplicantNotFoundException.java
  src/main/java/com/aliens/friendship/domain/matching/exception/DuplicatedMatchException.java
  src/main/java/com/aliens/friendship/domain/matching/exception/LanguageNotFoundException.java
  src/main/java/com/aliens/friendship/domain/matching/exception/MatchingExceptionCode.java
  src/main/java/com/aliens/friendship/domain/matching/exception/MatchingExceptionHandler.java
  src/main/java/com/aliens/friendship/domain/matching/exception/MatchingNotFoundException.java
  src/main/java/com/aliens/friendship/domain/matching/service/BlockingInfoService.java
  src/main/java/com/aliens/friendship/domain/matching/service/MatchingInfoService.java
  src/main/java/com/aliens/friendship/domain/member/controller/APIController.java
  src/main/java/com/aliens/friendship/domain/member/controller/MemberController.java
  src/main/java/com/aliens/friendship/domain/member/controller/NationalityController.java
  src/main/java/com/aliens/friendship/domain/member/service/MemberService.java
  src/test/java/com/aliens/friendship/emailAuthentication/controller/EmailAuthenticationControllerTest.java
  src/test/java/com/aliens/friendship/matching/controller/MatchingControllerTest.java
  src/test/java/com/aliens/friendship/matching/service/BlockingServiceTest.java
  src/test/java/com/aliens/friendship/matching/service/MatchingInfoServiceTest.java
  src/test/java/com/aliens/friendship/member/controller/NationalityControllerTest.java
Labels: 🔧fix, ⚙️refactor, 🔀merge, 리뷰 진짜 급함!!!!

#132 feat/backend-58 API Test 후 기능 및 반환값 수정
  src/main/java/com/aliens/friendship/domain/matching/controller/dto/ApplicantResponse.java
  src/main/java/com/aliens/friendship/domain/matching/controller/dto/PartnersResponse.java
  src/main/java/com/aliens/friendship/domain/matching/service/MatchingInfoService.java
  src/main/java/com/aliens/friendship/domain/member/controller/MemberController.java
  src/main/java/com/aliens/friendship/domain/member/controller/dto/JoinDto.java
  src/main/java/com/aliens/friendship/domain/member/controller/dto/MemberInfoDto.java
  src/main/java/com/aliens/friendship/domain/member/domain/Member.java
  src/main/java/com/aliens/friendship/domain/member/domain/Nationality.java
  src/main/java/com/aliens/friendship/domain/member/exception/InvalidMemberNameException.java
  src/main/java/com/aliens/friendship/domain/member/exception/MemberExceptionCode.java
  src/main/java/com/aliens/friendship/domain/member/exception/MemberExceptionHandler.java
  src/main/java/com/aliens/friendship/domain/member/exception/WithdrawnMemberWithinAWeekException.java
  src/main/java/com/aliens/friendship/domain/member/service/MemberService.java
  src/test/java/com/aliens/friendship/chatting/repository/MatchingRepositoryImplTest.java
  src/test/java/com/aliens/friendship/jwt/JwtAPITest.java
  src/test/java/com/aliens/friendship/jwt/JwtUtilTest.java
  src/test/java/com/aliens/friendship/matching/controller/MatchingControllerTest.java
  src/test/java/com/aliens/friendship/matching/controller/PartnersFixture.java
  src/test/java/com/aliens/friendship/matching/service/MatchingInfoServiceTest.java
  src/test/java/com/aliens/friendship/matching/service/MemberFixture.java
  src/test/java/com/aliens/friendship/member/controller/MemberControllerTest.java
  src/test/java/com/aliens/friendship/member/repository/MemberRepositoryImplTest.java
  src/test/java/com/aliens/friendship/member/service/MemberServiceTest.java
Labels: 🧪test, 🌟feat, ⚙️refactor, 리뷰 진짜 급함!!!!

#134 fix: 파일 경로 반환값 수정
  src/main/java/com/aliens/friendship/domain/member/service/MemberService.java
Labels: 🔧fix, 리뷰 얼마 안걸려요!!
