Repository 4Ailen/backend, pull requests merged in 2023-01, with the labels that each got.

#10 feat: response 관련 클래스 추가
  src/main/java/com/aliens/friendship/controller/ApiError.java
  src/main/java/com/aliens/friendship/controller/ApiRes.java
  src/main/java/com/aliens/friendship/controller/GlobalExceptionHandler.java
Labels: 🌟feat

#17 Feature/#12
  build.gradle
  src/main/java/com/aliens/friendship/FriendshipApplication.java
  src/main/java/com/aliens/friendship/domain/Applicant.java
  src/main/java/com/aliens/friendship/domain/Authentication.java
  src/main/java/com/aliens/friendship/domain/BlockingInfo.java
  src/main/java/com/aliens/friendship/domain/ChattingRoom.java
  src/main/java/com/aliens/friendship/domain/Language.java
  src/main/java/com/aliens/friendship/domain/Member.java
  src/main/java/com/aliens/friendship/domain/Nationality.java
  src/main/java/com/aliens/friendship/domain/Participant.java
  src/main/java/com/aliens/friendship/domain/Question.java
  src/main/java/com/aliens/friendship/repository/ApplicantRepository.java
  src/main/java/com/aliens/friendship/repository/AuthenticationRepository.java
  src/main/java/com/aliens/friendship/repository/BlockingInfoRepository.java
  src/main/java/com/aliens/friendship/repository/ChattingRoomRepository.java
  src/main/java/com/aliens/friendship/repository/LanguageRepository.java
  src/main/java/com/aliens/friendship/repository/MemberRepository.java
  src/main/java/com/aliens/friendship/repository/NationalityRepository.java
  src/main/java/com/aliens/friendship/repository/ParticipantRepository.java
  src/main/java/com/aliens/friendship/repository/QuestionRepository.java
  src/main/resources/application.properties
Labels: 🌟feat

#16 Feature/#2 매칭 알고리즘 테스트 기능 추가(TTL 적용)
  src/main/java/com/aliens/friendship/dto/BlockingInfo.java
  src/test/java/com/aliens/friendship/matching/MatchingTest.java
Labels: 🧪test

#36 Feat/#28 chatting 채팅 API 작성하기
  src/main/java/com/aliens/friendship/config/security/CustomUserDetails.java
  src/main/java/com/aliens/friendship/config/security/SecurityConfig.java
  src/main/java/com/aliens/friendship/controller/ChatController.java
  src/main/java/com/aliens/friendship/controller/ChattingController.java
  src/main/java/com/aliens/friendship/controller/RoomController.java
  src/main/java/com/aliens/friendship/domain/Chat.java
  src/main/java/com/aliens/friendship/domain/Chatting.java
  src/main/java/com/aliens/friendship/domain/ChattingRoom.java
  src/main/java/com/aliens/friendship/domain/MatchingParticipant.java
  src/main/java/com/aliens/friendship/domain/Member.java
  src/main/java/com/aliens/friendship/domain/Room.java
  src/main/java/com/aliens/friendship/domain/dto/JoinDto.java
  src/main/java/com/aliens/friendship/domain/dto/RoomInfoDto.java
  src/main/java/com/aliens/friendship/dto/ChatMessage.java
  src/main/java/com/aliens/friendship/repository/ChattingRepository.java
  src/main/java/com/aliens/friendship/repository/MemberRepository.java
  src/main/java/com/aliens/friendship/repository/RoomRepository.java
  src/main/java/com/aliens/friendship/service/ChatService.java
  src/main/java/com/aliens/friendship/service/MemberService.java
  src/main/java/com/aliens/friendship/util/BeforeData.java
  src/main/resources/templates/chat/roomList.html
Labels: 🌟feat

#34 Feature/#26 매칭 관련 코드
  .gitignore
  src/main/java/com/aliens/friendship/config/security/CustomUserDetailService.java
  src/main/java/com/aliens/friendship/config/security/CustomUserDetails.java
  src/main/java/com/aliens/friendship/config/security/SecurityConfig.java
  src/main/java/com/aliens/friendship/controller/MatchingController.java
  src/main/java/com/aliens/friendship/domain/Member.java
  src/main/java/com/aliens/friendship/domain/Question.java
  src/main/java/com/aliens/friendship/dto/ApplicantInfo.java
  src/main/java/com/aliens/friendship/dto/MatchedApplicants.java
  src/main/java/com/aliens/friendship/repository/MemberRepository.java
  src/main/java/com/aliens/friendship/repository/QuestionRepository.java
  src/main/java/com/aliens/friendship/service/MatchingService.java
  src/main/java/com/aliens/friendship/service/MemberService.java
  src/test/java/com/aliens/friendship/matching/MatchingTest.java
Labels: enhancement, 🌟feat

#43 merge: feat/#28 chatting -> develop
  src/main/java/com/aliens/friendship/config/security/CustomUserDetails.java
  src/main/java/com/aliens/friendship/config/security/SecurityConfig.java
  src/main/java/com/aliens/friendship/controller/ChatController.java
  src/main/java/com/aliens/friendship/controller/ChattingController.java
  src/main/java/com/aliens/friendship/controller/RoomController.java
  src/main/java/com/aliens/friendship/domain/Chat.java
  src/main/java/com/aliens/friendship/domain/Chatting.java
  src/main/java/com/aliens/friendship/domain/ChattingRoom.java
  src/main/java/com/aliens/friendship/domain/MatchingParticipant.java
  src/main/java/com/aliens/friendship/domain/Member.java
  src/main/java/com/aliens/friendship/domain/Room.java
  src/main/java/com/aliens/friendship/domain/dto/JoinDto.java
  src/main/java/com/aliens/friendship/domain/dto/RoomInfoDto.java
  src/main/java/com/aliens/friendship/dto/ChatMessage.java
  src/main/java/com/aliens/friendship/repository/ChattingRepository.java
  src/main/java/com/aliens/friendship/repository/MemberRepository.java
  src/main/java/com/aliens/friendship/repository/RoomRepository.java
  src/main/java/com/aliens/friendship/service/ChatService.java
  src/main/java/com/aliens/friendship/service/MemberService.java
  src/main/java/com/aliens/friendship/util/BeforeData.java
  src/main/resources/templates/chat/roomList.html
Labels: 🔀merge

#56 feat/#55_entity EmailAuthentication 상태값 추가
  src/main/java/com/aliens/friendship/emailAuthentication/domain/EmailAuthentication.java
Labels: 🌟feat, 리뷰 얼마 안걸려요!!

#58 refactor/#38 엔티티 상태값에 enum 설정
  src/main/java/com/aliens/friendship/emailAuthentication/domain/EmailAuthentication.java
  src/main/java/com/aliens/friendship/matching/domain/MatchingParticipant.java
  src/main/java/com/aliens/friendship/matching/service/MatchingService.java
  src/main/java/com/aliens/friendship/member/domain/Member.java
Labels: ⚙️refactor, 리뷰 얼마 안걸려요!!

#59 refactor/#37 builder default값 설정
  src/main/java/com/aliens/friendship/chatting/domain/ChattingRoom.java
  src/main/java/com/aliens/friendship/emailAuthentication/domain/EmailAuthentication.java
  src/main/java/com/aliens/friendship/matching/domain/MatchingParticipant.java
  src/main/java/com/aliens/friendship/matching/domain/Question.java
  src/main/java/com/aliens/friendship/matching/service/MatchingService.java
  src/main/java/com/aliens/friendship/member/domain/Member.java
Labels: ⚙️refactor, 리뷰 얼마 안걸려요!!

#54 feat/#39 매칭 인원 수정에 따른 매칭 서비스 코드 변경
  src/main/java/com/aliens/friendship/matching/controller/MatchingController.java
  src/main/java/com/aliens/friendship/matching/service/MatchingService.java
  src/main/java/com/aliens/friendship/matching/service/model/MatchedGroup.java
  src/test/java/com/aliens/friendship/matching/MatchingTest.java
Labels: 🌟feat

#57 docs: 어플 소개 readme에 추가
  README.md
Labels: 📄docs, 리뷰 얼마 안걸려요!!

#66 fix: MatchingService에서 enum사용하도록 수정
  src/main/java/com/aliens/friendship/matching/service/MatchingService.java
Labels: 리뷰 얼마 안걸려요!!

#67 Refactor/#50 method naming
  src/main/java/com/aliens/friendship/matching/domain/MatchingParticipant.java
  src/main/java/com/aliens/friendship/matching/service/MatchingService.java
  src/main/java/com/aliens/friendship/member/domain/Member.java
Labels: ⚙️refactor, 리뷰 진짜 급함!!!!, 리뷰 얼마 안걸려요!!
