Repository 4Ailen/backend, pull requests merged in 2023-10, with the labels that each got.

#228 refactor: 매칭 완료 알림
  membership/build.gradle
  membership/src/main/java/com/aliens/friendship/domain/admin/AdminMemberController.java
  membership/src/main/java/com/aliens/friendship/domain/fcm/converter/FcmMessageConverter.java
  membership/src/main/java/com/aliens/friendship/domain/fcm/service/FcmService.java
  membership/src/main/java/com/aliens/friendship/domain/match/business/MatchBusiness.java
  membership/src/main/java/com/aliens/friendship/global/rabbitMQ/MatchCompletionProducer.java
Labels: ⚙️refactor

#230 fix: 게시글 삭제 오류 해결
  db/src/main/java/com/aliens/db/communityarticle/entity/CommunityArticleEntity.java
  db/src/main/java/com/aliens/db/marketarticle/entity/MarketArticleEntity.java
Labels: 🔧fix, 리뷰 얼마 안걸려요!!

#232 Refactor/#231 querydsl config
  db/build.gradle
  db/src/main/java/com/aliens/db/QuerydslConfig.java
Labels: ⚙️refactor, 리뷰 얼마 안걸려요!!

#238 fix: 이미지 반환 시 url로 반환되도록 수정
  membership/src/main/java/com/aliens/friendship/domain/applicant/converter/ApplicantConverter.java
  membership/src/main/java/com/aliens/friendship/domain/personalNotice/service/PersonalNoticeService.java
Labels: 🔧fix, 리뷰 얼마 안걸려요!!

#241 fix/ 신청시 중복된 신청 행위일 경우 예외를 던지도록 수정
  membership/src/main/java/com/aliens/friendship/domain/applicant/business/ApplicantBusiness.java
  membership/src/main/java/com/aliens/friendship/domain/applicant/service/ApplicantService.java
Labels: 🔧fix
